services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    expose:
      - 27017
    ports:
      - '27017:27017'
  express:
    container_name: express
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongo
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - mongo

volumes:
  mongo:
